baseURL = 'https://beardedcrackie.github.io/'
languageCode = 'en-us'
title = 'Bearded Crackie'
theme = 'nightfall'

# Enable multilingual support
defaultContentLanguage = "sk"

[languages]
  [languages.en]
    languageName = "English"
    weight = 2
    title = "Bearded Crackie's Blog"

  [languages.sk]
    languageName = "Slovak"
    weight = 1
    title = "Blog Bearded Crackieho"
    contentDir = "content/sk"
    [languages.sk.menu]
      [[languages.sk.menu.header]]
        name = "about_me"
        url = "/sk/about/"
        weight = 2

[params]
  user = "hello"
  hostname = "beardedcrackie"
  readingTime = false  # Show reading time on post page
  published = false  # Show published data on post pages

[params.author]
  name = "Bearded Crackie"


[[params.social]]
key = 0
name = "github"
url = "https://github.com/beardedcrackie"
#icon = "fa-brands fa-github"  # Add link to your icon font to `layouts/partials/custom-head.html`
target = "_blank" # Defines your target option in a-href. _blank for a new Tab for example.
aria = "GitHub Profile" # Define the aria label for accessibility like page reader - this is better for your SEO
